#!/bin/bash

clear

for program in apache2 bind9 cain cracklib hydra john nc netcat nginx postgresql samba telnet tftp-server vsftpd
do
	which $program >> output
done
for files in *.jpg *.mp3 *.mp4 *.png
do
	find /home -name $files >> output
done

ls /home > users 
cat users | while read users
do
	echo -e $users:"Goodpassword123!" | chpasswd
done
rm users
echo "Default password [Goodpassword123!] has been set"
sleep 1
clear

# Red Hat Enterprise Linux 6 stig viewers
# sets file to be group-owned by root
# V-38448 V-38451 V-38459 V-38503 V-38581
for groupown in /etc/gshadow /etc/password /etc/group /etc/shadow /boot/grub/grub.conf
do
	chgrp root $groupown
done
# sets file to be owned by root
# V-38443 V-38450 V-38458 V-38502 V-38579
for own in /etc/gshadow /etc/password /etc/group /etc/shadow /boot/grub/grub.conf
do
	chown root $own
done
# sets file to specific permission
# V-38449 V-38457 V-38461 V-38504 V-38583
chmod 0000 /etc/gshadow
chmod 0644 /etc/passwd
chmod 0644 /etc/group
chmod 0000 /etc/shadow
chmod 0600 /boot/grub/grub.conf
# V-38588	disable interactive booting (add or correct "PROMPT=no")
gedit /etc/sysconfig/init
# V-38603	uninstall ypserv package(?)
apt-get purge ypserv
# V-38604	sets ypbind service (allow system to act as NIS or NIS+ domain)to be off
chkconfig ypbind off
service ypbind stop
# V-38605	sets crond service to be on
chkconfig crond on
service crond start
# V-38691	disable bluetooth service
chkconfig bluetooth off
service bluetooth stop

# Oracle Linux 6 stig viewers
# V-50787	All system command files must have mode 755 or less permissive
for mode755 in /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin
do
	chmod go-w $mode755
done

clear

passwd -l root
clear
echo "Root account password secured."
sleep 1
clear

if ! grep "allow-guest=false" /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf > /dev/null
then
	echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
fi
echo "Guest account is disabled."
sleep 1
clear

sed -i -e "s/PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/ssh_config
sed -i -e "s/PermitRootLogin yes/PermitRootLogin no/" /etc/ssh/sshd_config
sed -i -e "s/# Port 22/Port 222/" /etc/ssh/sshd_config
service sshd restart
echo "SSH and SSHD policies have been set."
echo "SSH is now on port 222"
sleep 1
clear

sed -i -e "s/obscure sha512/obscure sha512 minlen=12 retry=3/" /etc/pam.d/common-password
sed -i -e "s/PASS_MAX_DAYS	99999/PASS_MAX_DAYS	60/" /etc/login.defs
sed -i -e "s/PASS_MIN_DAYS	0/PASS_MIN_DAYS	59/" /etc/login.defs
echo "Password policy has been set."
sleep 1
clear

sed -i -e "s/alias net-pf-10 off/alias ipv6 off/" /etc/modprobe.d/aliases
echo "IPv6 is disabled"
clear

# make sure nothing is in this file
gedit /etc/rc.local

clear
read -p "Proper update settings have been set? Press [enter] continue."

# install and enable firewall, along with other useful stuff
apt-get -y update
apt-get -y upgrade
for installs in apparmor bastille chkrootkit clamav lynis rkhunter ufw
do
	apt-get -y install $installs
done
ufw enable
/usr/sbin/chkrootkit > chkrootkit
bastille -c
clear

# some other stuffs
for permissions in /etc/hosts.allow /etc/mtab /etc/profile /etc/syslog.pid /etc/utmp /var/adm/wtmp /var/log/wtmp /var/run/syslog.pid /etc/inittab /etc/sysctl.conf
do
	chmod 0700 $permissions
done
gedit /etc/resolv.conf
gedit /etc/hosts
gedit /etc/passwd
gedit /etc/shadow
echo 'vm.swappiness=1' >> /etc/sysctl.conf



clear
echo "End of script"
sleep 1
clear
