#!/bin/bash

: <<'SKIP'
ls /home > users
cat users | while read users
do
	echo -e $users:"brandnewpassword" | chpasswd
done
sed -i -e "s/PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/ssh_config
sed -i -e "s/PermitRootLogin yes/PermitRootLogin no/" /etc/ssh/sshd_config
sed -i -e "s/obscure sha512/obscure sha512 minlen=12 retry=3/" /etc/pam.d/common-password
sed -i -e "s/PASS_MAX_DAYS	99999/PASS_MAX_DAYS	60/" /etc/login.defs
sed -i -e "s/PASS_MIN_DAYS	0/PASS_MIN_DAYS	59/" /etc/login.defs
if ! grep "ENCRYPT_METHOD SHA512" /etc/login.defs > /dev/null
then
	gedit /etc/login.defs
fi
# enforces password history
sed -i -e "s/password sufficient pam_unix.so use_authtok/password sufficient pam_unix.so use_authtok md5 shadow remember=13/" /etc/pam.d/common-password

# system update
clear
echo "Set proper password policy"
read -p "Update policy has been properly set? [y/n] " policy
while [ $policy == "n" ] || [ $policy == "no" ] || [ $policy == "N" ] || [ $policy == "NO" ] || [ $policy == "No" ]
do
	read -p "Update policy has been properly set? [y/n] " policy
done

read -p "Proceed with update? [y/n] " yesno
if [ $yesno == "y" ] || [ $yesno == "yes" ] || [ $yesno == "Y" ] || [ $yesno == "YES" ] || [ $yesno == "Yes" ]
then
	apt-get -y update
	apt-get -y upgrade
else
	echo "Remember to perform the update" > /home/$current/Desktop
fi

CurrentUser ()
{
	current = "$(whoami)"
}

CopyToDesktop ()
{
	
}

SKIP
